# Generated by Django 4.1.5 on 2023-06-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
